### ISSUE TITLE
z-index issues with Thebe controls

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/myst-theme#140]
![image](https://github.com/executablebooks/myst-theme/assets/913249/930c70df-8961-427f-98e0-e6bfce41f0d8)

**Comment by stevejpurves** [comment]
the top toolbar we have control over, but the slider themselves are being rendered with ipywidgets styles. This is not limited to the sliders btw, other things in jupyter outputs areas can have varied z-indexes. The toolbar controls were pushed to a higher layer in order to keep them on top of various parts of outputs. pushing the menu itself to a higher z-index isn't an option?

**Comment by stevejpurves** [comment]
consider only lifting the nav and gray background overlay up (z-10) when the menu is open on narrow screens
